### ISSUE TITLE
Fails with a punctuation character

### ISSUE THREAD

**Issue by Telavian** [UglyToad/PragmaticSegmenterNet#1]
Trying to segment the single character '.' is failing.

**Comment by EliotJones** [comment]
Well that's embarrassing! Thanks, I'll take a look this evening.

**Comment by EliotJones** [comment]
I've pushed a version which I think should fix this issue as well as prevent the underlying bug recurring for longer sequences of text. Please take a look at version 1.0.1 and see if it resolves your problem: https://www.nuget.org/packages/PragmaticSegmenterNet/1.0.1

Thanks again for letting me know about this.

**Comment by Telavian** [comment]
Thanks. It works great.
