### ISSUE TITLE
Chinese text fails to parse

### ISSUE THREAD

**Issue by Telavian** [UglyToad/PragmaticSegmenterNet#2]
It appears the following text is failing to parse correctly.

初次评价: 08.27
打印机很好使，客服也很耐心，物流也挺快的，最重要的是打印机很轻，外观好看，打印速度也可以。打印照片的话因为只有三色，所以有点偏色，打印照片的话最好调一下色，这个价位很可以了，五星好评～ 推出结论：应该早点买的(๑˙ー˙๑)
收货7天后追加：很好用，最主要是真的很方便，排版格式可以自己定，而且客服很耐心。一瓶墨水应该能用很长时间，早买要划算，去年光打印的钱都值这台打印机了，祝卖家生意兴隆~(๑˙ー˙๑)

**Comment by Telavian** [comment]
Appears to be an issue with badly formatted input text. \r and \n characters are encoded as is in the text and not as control characters. Converting them to control characters instead of '\n' for instance fixes it.

So bad input creates bad output.

**Comment by EliotJones** [comment]
Glad to hear it worked out ok, let me know if you run into any issues with the Chinese segmentation in general, it's one of the harder bits to know how to test :)
