### ISSUE TITLE
Parenthesis cause segmenter to greatly expand text

### ISSUE THREAD

**Issue by Telavian** [UglyToad/PragmaticSegmenterNet#7]
When attempting to segment the text below: (period is needed)
('$0 xyz, $0 abc, $0 def').

The segmenter enters a loop and produces results that are massively expanded.
Removing the parenthesis characters '(' and ')' produces valid results.

**Comment by Telavian** [comment]
Sorry. Ultimately it appears to be the $0.

**Comment by EliotJones** [comment]
Thanks for the bug report, I've pushed up a fix for this case now. Would it be helpful to have this released as part of the official NuGet package as soon as possible or are you building from source?

**Comment by Telavian** [comment]
I use nuget.

**Comment by EliotJones** [comment]
Hi Telavian, I've now updated the version available on NuGet to include this fix. Please give version 1.0.3 a go and let me know if it works.
https://www.nuget.org/packages/PragmaticSegmenterNet/1.0.3

**Comment by Telavian** [comment]
Thanks. Your library is amazingly helpful.
