### ISSUE TITLE
Segmenter fails with non-breaking space

### ISSUE THREAD

**Issue by LosDavidos** [UglyToad/PragmaticSegmenterNet#8]
Hi
I have a following text 

> Trututu 1. second trututu 2. other trututu

Class ListItemReplacer fails on method ScanLists when analyzing this text with error code 'Input string was not in correct format'
It happens because instead of space chars before numbers there are non-break space chars (U+00A0)

**Comment by EliotJones** [comment]
Thanks for the issue report, I've pushed a fix for this here: https://www.nuget.org/packages/PragmaticSegmenterNet/1.0.5

Please give it a go and let me know if it fixes the issue.

**Comment by LosDavidos** [comment]
Looks like everything works fine. Thanks for quick fix!
